"""Download AG News, take a small subset, and save it locally as Parquet.

Why this module exists:
    Data ingestion is kept separate from training. The dataset is downloaded and
    prepared once, the subset is reproducible (fixed seed), and the training code
    only ever reads a local, ready-to-use dataset -- it never knows about HuggingFace
    or downloads.

Run it from the repo root with:
    uv run python data/data_fetcher.py
"""

from pathlib import Path

from datasets import load_dataset

# --- Configuration (kept simple for Phase 0) ---
DATASET_ID = "fancyzhx/ag_news"   # canonical AG News on the HF Hub (datasets 5.x)
DATA_DIR = Path("data/downloads")   # output dir (gitignored); regenerated by this script
TRAIN_SIZE = 5000
VAL_SIZE = 1000
SEED = 42


def fetch_data() -> None:
    """Download AG News, build train/validation subsets, and write them as Parquet."""
    raw = load_dataset(DATASET_ID)

    train_subset = raw["train"].shuffle(seed=SEED).select(range(TRAIN_SIZE))
    # Validation comes from the official test split, kept fully separate from train.
    val_subset = raw["test"].shuffle(seed=SEED).select(range(VAL_SIZE))

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    train_path = DATA_DIR / "train.parquet"
    val_path = DATA_DIR / "validation.parquet"
    train_subset.to_parquet(train_path)
    val_subset.to_parquet(val_path)

    print(f"Wrote {len(train_subset)} train rows -> {train_path}")
    print(f"Wrote {len(val_subset)} validation rows -> {val_path}")


if __name__ == "__main__":
    fetch_data()
